name: BountySystem
main: com.lavishmc.bountysystem.BountySystem
version: '${version}'
api-version: '1.21'
softdepend: [Vault, HeadHunter]
commands:
  bounty:
    description: Open the bounty menu or place a bounty
    usage: /bounty [place <player> <amount>]
